version: '1'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: 
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  oppie:
    build:
      dockerfile: Dockerfile
    volumes:
      - "./src:/src"
      - /var/run/docker.sock:/var/run/docker.sock
      - ollama:/root/.ollama
    env_file:
      - config/.env
    networks:
      - mynetwork
    depends_on:
      - ollama
    privileged: true

networks:
  mynetwork:
    driver: bridge

volumes:
  ollama:
    driver: local